/////////////////
// CHALLENGE 1 //
/////////////////
function Challenge1(){
  let myChallenge1 = document.getElementById("displayChallenge");
  if (myChallenge1.style.display == "none") { myChallenge1.style.display = "block"; }
  else { myChallenge1.style.display = "none"; }

  const content = {
    header      : "<h3>Challenge 1 (Multiples of 3 or 5)</h3>",
    informations: "<p>If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.<br>" +
                  "Find the sum of all the multiples of 3 or 5 below the input number.</p>",
    input       : "<div> <label for='Input-1'>Input</label> <input id='Input-1' type='number' placeholder='Enter your input'>",
    button      : "<button id='Button1' onclick='calculation1()'>ENTER</button> <br>",
    info        : "<span id='displayInfo'></span> <br>",
    answer      : "<span id='Answer-1'></span> </div>"
  };

  myChallenge1.innerHTML = content.header + content.informations + content.input + content.button + content.info + content.answer;
}

function calculation1(){
  let myInput = document.getElementById("Input-1").value;
  document.getElementById("Answer-1").innerText = "Sum of all multiples of 3 or 5 = " + multiplesOf3Or5(myInput);
}

function multiplesOf3Or5(input) {
  let listMultiplesOf3 = [];
  let listMultiplesOf5 = [];
  let listMultiplesOf3Or5 = [];
  let sum = 0;

  /* Checking the number is multiples of either 3 or 5 */
  for(let i=1; i<input; i++){
      if (i%3 === 0 || i%5 === 0){
          listMultiplesOf3Or5.push(i);
          if (i%3 === 0) { listMultiplesOf3.push(i); }
          if (i%5 === 0) { listMultiplesOf5.push(i); }
      };
  };
  document.getElementById("displayInfo").innerText = "Multiples of 3 or 5 = " + listMultiplesOf3Or5;

  /* Sum of all multiples 3 or 5 below input value */
  for(let i=0; i<listMultiplesOf3Or5.length; i++){
      sum += listMultiplesOf3Or5[i];
  };
  return sum;
};

/////////////////
// CHALLENGE 2 //
/////////////////
function Challenge2(){
  let myChallenge2 = document.getElementById("displayChallenge");
  if (myChallenge2.style.display == "none") { myChallenge2.style.display = "block"; }
  else { myChallenge2.style.display = "none"; }

  const content = {
    header      : "<h3>Challenge 2 (Even Fibonacci Numbers)</h3>",
    informations: "<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms.<br>" +
                  "By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...<br>" +
                  "By considering the terms in the Fibonacci sequence whose values do not exceed input number, find the sum of the even-valued terms.</p>",
    input       : "<div><label for='Input-2'>Input</label> <input id='Input-2' type='number' placeholder='Enter your input'> ",
    button      : "<button id='Button2' onclick='calculation2()'>ENTER</button> <br>",
    info        : "<span id='displayInfo'></span> <br>", 
    answer      : "<span id='Answer-2'></span></div>"
  };
  myChallenge2.innerHTML = content.header + content.informations + content.input + content.button + content.info + content.answer;
}

function calculation2(){
  let myInput = document.getElementById("Input-2").value;
  document.getElementById("Answer-2").innerText = "Sum of all even Fibonacci Number = " + fiboEvenSum(myInput);
}

function fiboEvenSum(input) {
  let previous = 1;
  let current = 2;
  let sumOfEven = 0;
  /* 1 and 2 is the starting operand in fibonacci */
  let fibo = [previous, current];
  
  /* Checking sum of all even fibonacci numbers is below the input value */
  for (let i=2; current<=input; i++) {
    /* Checking input value is even number or not */
    if ( current%2 === 0) {
      sumOfEven += current;
    }
    /* Listing*/
    [previous, current] = [current, previous + current];
    fibo.push(current);
  }
  document.getElementById("displayInfo").innerText = "List of Fibonacci Number" + " = " + fibo;
  return sumOfEven;
};

/////////////////
// CHALLENGE 3 //
/////////////////
function Challenge3(){
  let myChallenge3 = document.getElementById("displayChallenge");
  if (myChallenge3.style.display == "none") { myChallenge3.style.display = "block"; }
  else { myChallenge3.style.display = "none"; }

  const content = {
    header      : "<h3>Challenge 3 (Largest Prime Factor)</h3>",
    informations: "<p>The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of any given number?</p>",
    input       : "<div><label for='Input-3'>Input</label> <input id='Input-3' type='number' placeholder='Enter your input'> ",
    button      : "<button id='Button3' onclick='calculation3()'>ENTER</button> <br>",
    info        : "<span id='displayInfo'></span> <br>", 
    answer      : "<span id='Answer-3'></span></div>"
  };
  myChallenge3.innerHTML = content.header + content.informations + content.input + content.button + content.info + content.answer;
}

function calculation3(){
  let myInput = document.getElementById("Input-3").value;
  document.getElementById("Answer-3").innerText = "The largest prime factor is " + largestPrimeFactor(myInput);
}

function largestPrimeFactor(number) {
  let prime = 2;
  let max = 0;
  let listMax = [];
  while(prime <= number){
    if (number%prime === 0){
      max = prime;
      number /= prime;
    }
    else {
      prime++;
    }
  }
  return max;
}

/////////////////
// CHALLENGE 4 //
/////////////////
function Challenge4(){
  let myChallenge4 = document.getElementById("displayChallenge");
  if (myChallenge4.style.display == "none") { myChallenge4.style.display = "block"; }
  else { myChallenge4.style.display = "none"; }

  const content = {
    header      : "<h3>Challenge 4 (Largest palindrome product)</h3>",
    informations: "<p>The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99. <br>" +
                  "Find the largest palindromic number made from the product of two <em>n</em>-digit numbers.</p>",
    input       : "<div><label for='Input-4'>Input</label> <input id='Input-4' type='number' placeholder='Enter your input'> ",
    button      : "<button id='Button4' onclick='Calculation4()'>ENTER</button> <br>",
    info        : "<span id='displayInfo'></span> <br>",
    answer      : "<span id='Answer-4'></span></div>",
    insights    :
      "<div><b>INSIGHTS</b>" +
      "<div><u>Palindromic Number</u> is a number that reads the same forward and backward </div>" +
      "<div>Example: 0, 1, 2, 3, ..., 9, 11, 22, 33, ..., 99, 101, 111, 121, 131, ..., 999, 1001, 1111, 1221, 1331, ...</div>" + 
      "<pre><div class=\"Indent-Level1\">let <em>myInput</em> = 1023; // User enter any number </div>" +
      "<div class=\"Indent-Level1\">let <em>myInputString</em> = String(<em>myInput</em>); // \"1023\" (Change the input's data type from number to string) </div>" +
      "<div class=\"Indent-Level1\">let <em>myInputSplit</em> = <em>myInputString</em>.split(\"\"); // [\"1\", \"0\", \"2\", \"3\"] (Split each character into array) </div>" +
      "<div class=\"Indent-Level1\">let <em>myInputReversed</em> = <em>myInputSplit</em>.reverse(); // [\"3\", \"2\", \"0\", \"1\"] (Reverse all data backwards) </div>" +
      "<div class=\"Indent-Level1\">let <em>myInputJoined</em> = <em>myInputReversed</em>.join(\"\"); // \"3201\" (Join all data into a string) </div>" +
      "<div class=\"Indent-Level1\">if (<em>myInputString</em> == <em>myInputJoined</em>) // The statement is comparing both data </div>" +
      "<div class=\"Indent-Level2\">console.log(\"Palindrome\"); // Return \"Palindrome\" if the statement is true </div>" +
      "<div class=\"Indent-Level1\">else </div>" +
      "<div class=\"Indent-Level2\">console.log(\"Not palindrome\"); // Return \"Not palindrome\" if the statement is false</div>" +
      "</pre>" +
      "</div>"
  };

  myChallenge4.innerHTML = content.header + content.informations + content.input + content.button + content.info + content.answer + content.insights;
}

function Calculation4(){
  let myInput = document.getElementById("Input-4").value;
  document.getElementById("Answer-4").innerHTML = "The largest palindrome product from 2 " + myInput + "-digits number is " + largestPalindromeProduct(myInput);

  function largestPalindromeProduct(digit) {
    let maxDigit = 10**digit;
    let product = 1;
    let numberInString = "";
    let reversedString = "";
    let listOfPalindrome = [];

    for (let multiplicand1=maxDigit/10; multiplicand1<maxDigit; multiplicand1++) {
      for(let multiplicand2=maxDigit/10; multiplicand2<maxDigit; multiplicand2++) {
        product = multiplicand1*multiplicand2;
        numberInString = product.toString();
        reversedString = numberInString.split("").reverse().join("");

        if (numberInString == reversedString)
          listOfPalindrome.push(numberInString);
      }
    }
    return Math.max(...listOfPalindrome);
  }
}

/////////////////
// CHALLENGE 5 //
/////////////////
function Challenge5() {
  let myChallenge5 = document.getElementById("displayChallenge");
  if (myChallenge5.style.display == "none") { myChallenge5.style.display = "block"; }
  else { myChallenge5.style.display = "none"; }

  const content = {
    header      : "<h3>Challenge 5 (Smallest multiple)</h3>",
    informations: "<p>2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.<br>" +
                  "What is the smallest positive number that is evenly divisible by all of the numbers from 1 to <em>n</em>?</p>",
    input       : "<div> <label for='Input-5'>Input</label> <input id='Input-5' type='number' placeholder='Enter your input'>",
    button      : "<button id='Button5' onclick='Calculation5()'>ENTER</button><br>",
    info        : "<span id='displayInfo'><br></span>",
    answer      : "<span id='Answer-5'></span></div><br>",
    insights    :
      "<div><b>INSIGHTS</b>" +
      "<div><u>Lowest Common Multiple</u>, denoted with lcm(a, b) is the smallest positive integer that is divisible by both a and b</div>" +
      "<div>The lcm(a, b) can be determined with a very basic method by using multiples of number</div>" +
      "<div>The method is simply list all the multiples of each numbers and compare which one is the smallest number among them</div>" +
      "<div class=\"Indent-Level1\">Multiples of 1 &rarr; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...</div>" +
      "<div class=\"Indent-Level1\">Multiples of 2 &rarr; 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, ...</div>" +
      "<div class=\"Indent-Level1\">Multiples of 3 &rarr; 3, 6, 9, 12, 15, 18, 21, 24, 27, 30 ...</div>" +
      "<div class=\"Indent-Level1\">Multiples of 4 &rarr; 4, 8, 12, 16, 20, 24, 28, 32, 36, 40 ...</div>" +
      "<div class=\"Indent-Level1\">Multiples of 5 &rarr; 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, ...</div>" +
      "<div class=\"Indent-Level1\">Multiples of 6 &rarr; 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, ...</div>" +
      "<div class=\"Indent-Level1\">Multiples of 7 &rarr; 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, ...</div>" +
      "<div class=\"Indent-Level1\">Multiples of 8 &rarr; 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, ...</div>" +
      "<div class=\"Indent-Level1\">Multiples of 9 &rarr; 9, 18, 27, 36, 43, 54, 63, 72, 81, 90, ...</div>" +
      "<div class=\"Indent-Level1\">Multiples of 10 &rarr; 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, ...</div>" +
      "<div>Since this is a simple method, the process itself takes time when greater numbers involved</div><br>" +

      "<div><u>Prime Factorization</u> is used to overcome the issue</div>" +
      "<div>This is one of the method to find lcm(a, b) with greater numbers in a short time</div>" +
      "<div>The lcm(a, b) is determine by the product of all prime factors with the highest degree for those numbers</div>" +
      "<div class=\"Indent-Level1\">Prime factor of 1 &rarr; 2<sup>0</sup></div>" +
      "<div class=\"Indent-Level1\">Prime factor of 2 &rarr; 2<sup>1</sup></div>" +
      "<div class=\"Indent-Level1\">Prime factor of 3 &rarr; 2<sup>0</sup>.3<sup>1</sup></div>" +
      "<div class=\"Indent-Level1\">Prime factor of 4 &rarr; 2<sup>2</sup></div>" +
      "<div class=\"Indent-Level1\">Prime factor of 5 &rarr; 2<sup>0</sup>.3<sup>0</sup>.5<sup>1</sup></div>" +
      "<div class=\"Indent-Level1\">Prime factor of 6 &rarr; 2<sup>1</sup>.3<sup>1<sup></div>" +
      "<div class=\"Indent-Level1\">Prime factor of 7 &rarr; 2<sup>0</sup>.3<sup>0</sup>.5<sup>0</sup>.7<sup>1</sup></div>" +
      "<div class=\"Indent-Level1\">Prime factor of 8 &rarr; 2<sup>3</sup></div>" +
      "<div class=\"Indent-Level1\">Prime factor of 9 &rarr; 3<sup>2</sup></div>" +
      "<div class=\"Indent-Level1\">Prime factor of 10 &rarr; 2<sup>1</sup>.5<sup>1</sup></div><br>" +

      "<div>Therefore, all methods conclude that:</div>" +
      "<div class=\"Indent-Level1\">lcm(1, 2) = 2<sup>1</sup> = 2</div>" +
      "<div class=\"Indent-Level1\">lcm(1, 2, 3) = 2<sup>1</sup>.3<sup>1</sup> = 6</div>" +
      "<div class=\"Indent-Level1\">lcm(1, 2, 3, 4) = 2<sup>2</sup>.3<sup>1</sup> = 12</div>" +
      "<div class=\"Indent-Level1\">lcm(1, 2, 3, 4, 5) = 2<sup>2</sup>.3<sup>1</sup>.5<sup>1</sup> = 60</div>" +
      "<div class=\"Indent-Level1\">lcm(1, 2, 3, 4, 5, 6) = 2<sup>2</sup>.3<sup>1</sup>.5<sup>1</sup> = 60</div>" +
      "<div class=\"Indent-Level1\">lcm(1, 2, 3, 4, 5, 6, 7) = 2<sup>2</sup>.3<sup>1</sup>.5<sup>1</sup>.7<sup>1</sup> = 420</div>" +
      "<div class=\"Indent-Level1\">lcm(1, 2, 3, 4, 5, 6, 7, 8) = 2<sup>3</sup>.3<sup>1</sup>.5<sup>1</sup>.7<sup>1</sup> = 840</div>" +
      "<div class=\"Indent-Level1\">lcm(1, 2, 3, 4, 5, 6, 7, 8, 9) = 2<sup>3</sup>.3<sup>2</sup>.5<sup>1</sup>.7<sup>1</sup> = 2520</div>" +
      "<div class=\"Indent-Level1\">lcm(1, 2, 3, 4, 5, 6, 7, 8, 9, 10) = 2<sup>3</sup>.3<sup>2</sup>.5<sup>1</sup>.7<sup>1</sup> = 2520</div>" +
      "</div>"
  };

  myChallenge5.innerHTML = content.header + content.informations + content.input + content.button + content.info + content.answer + content.insights;
}

function Calculation5(){
  let myInput = document.getElementById("Input-5").value;
  document.getElementById("Answer-5").innerHTML = smallestMult(1, myInput);

  function smallestMult(divisor1, divisor2) {
    for (let i=divisor1; divisor1<=divisor2; divisor1++){
      
    }
    document.getElementById("displayInfo").innerHTML = 
    "<div>The divisors are ranged from 1 to " + divisor2 + "</div>";
    return divisor2;
  }
}