/////////////////
// CHALLENGE 1 //
/////////////////
function Challenge1(){
  let myChallenge1 = document.getElementById("displayChallenge");
  if (myChallenge1.style.display == "none") { myChallenge1.style.display = "block"; }
  else { myChallenge1.style.display = "none"; }

  const content = {
    header: "<h3>Challenge 1 (Multiples of 3 or 5)</h3>",
    information1: "<p>If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. ",
    information2: "The sum of these multiples is 23. <br> Find the sum of all the multiples of 3 or 5 below the input number.</p>",
    input: "<div><label for='Input-1'>Input</label> <input id='Input-1' type='number' placeholder='Enter your input'> ",
    button: "<button id='Button1' onclick='calculation1()'>ENTER</button> <br>",
    info: "<span id='displayInfo'></span> <br>",
    answer: "<span id='Answer-1'></span></div>"
  };

  myChallenge1.innerHTML = content.header + content.information1 + content.information2 + content.input + content.button + content.info + content.answer;
}

function calculation1(){
  let myInput = document.getElementById("Input-1").value;
  document.getElementById("Answer-1").innerText = "Sum of all multiples of 3 or 5 = " + multiplesOf3Or5(myInput);
}

function multiplesOf3Or5(input) {
  let listMultiplesOf3 = [];
  let listMultiplesOf5 = [];
  let listMultiplesOf3Or5 = [];
  let sum = 0;

  /* Checking the number is multiples of either 3 or 5 */
  for(let i=1; i<input; i++){
      if (i%3 === 0 || i%5 === 0){
          listMultiplesOf3Or5.push(i);
          if (i%3 === 0) { listMultiplesOf3.push(i); }
          if (i%5 === 0) { listMultiplesOf5.push(i); }
      };
  };
  document.getElementById("displayInfo").innerText = "Multiples of 3 or 5 = " + listMultiplesOf3Or5;

  /* Sum of all multiples 3 or 5 below input value */
  for(let i=0; i<listMultiplesOf3Or5.length; i++){
      sum += listMultiplesOf3Or5[i];
  };
  return sum;
};

/////////////////
// CHALLENGE 2 //
/////////////////
function challenge2(){
  let myChallenge2 = document.getElementById("displayChallenge");
  if (myChallenge2.style.display == "none") { myChallenge2.style.display = "block"; }
  else { myChallenge2.style.display = "none"; }
  const content = { header: "<h3>Challenge 2 (Even Fibonacci Numbers)</h3>",
                    information1: "<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. <br>",
                    information2: "By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... <br>",
                    information3: "By considering the terms in the Fibonacci sequence whose values do not exceed input number, find the sum of the even-valued terms.</p>",
                    input: "<div><label for='Input-2'>Input</label> <input id='Input-2' type='number' placeholder='Enter your input'> ",
                    button: "<button id='Button2' onclick='calculation2()'>ENTER</button> <br>",
                    info: "<span id='displayInfo'></span> <br>", 
                    answer: "<span id='Answer-2'></span></div>"
  };
  myChallenge2.innerHTML = content.header + content.information1 + content.information2 + content.information3 + content.input + content.button + content.info + content.answer;
}

function calculation2(){
  let myInput = document.getElementById("Input-2").value;
  document.getElementById("Answer-2").innerText = "Sum of all even Fibonacci Number = " + fiboEvenSum(myInput);
}

function fiboEvenSum(input) {
  let previous = 1;
  let current = 2;
  let sumOfEven = 0;
  /* 1 and 2 is the starting operand in fibonacci */
  let fibo = [previous, current];
  
  /* Checking sum of all even fibonacci numbers is below the input value */
  for (let i=2; current<=input; i++) {
    /* Checking input value is even number or not */
    if ( current%2 === 0) {
      sumOfEven += current;
    }
    /* Listing*/
    [previous, current] = [current, previous + current];
    fibo.push(current);
  }
  document.getElementById("displayInfo").innerText = "List of Fibonacci Number" + " = " + fibo;
  return sumOfEven;
};

/////////////////
// CHALLENGE 3 //
/////////////////
function challenge3(){
  let myChallenge3 = document.getElementById("displayChallenge");
  if (myChallenge3.style.display == "none") { myChallenge3.style.display = "block"; }
  else { myChallenge3.style.display = "none"; }
  const content = { header: "<h3>Challenge 3 (Largest Prime Factor)</h3>",
                    information1: "<p>The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of any given number?</p>",
                    input: "<div><label for='Input-3'>Input</label> <input id='Input-3' type='number' placeholder='Enter your input'> ",
                    button: "<button id='Button3' onclick='calculation3()'>ENTER</button> <br>",
                    info: "<span id='displayInfo'></span> <br>", 
                    answer: "<span id='Answer-3'></span></div>"
  };
  myChallenge3.innerHTML = content.header + content.information1 + content.input + content.button + content.info + content.answer;
}

function calculation3(){
  let myInput = document.getElementById("Input-3").value;
  document.getElementById("Answer-3").innerText = "The largest prime factor is " + largestPrimeFactor(myInput);
}

function largestPrimeFactor(number) {
  let prime = 2;
  let max = 0;
  let listMax = [];
  while(prime <= number){
    if (number%prime === 0){
      max = prime;
      number /= prime;
    }
    else {
      prime++;
    }
  }
  return max;
}